### ISSUE TITLE
Make the PATH dynamic

### ISSUE THREAD

**Issue by bahiirwa** [simplycomputing/sc-display-code#2]
This line needs to be dynamic in nature if the plugin is to become extensible for other site usage.

https://github.com/simplycomputing/sc-display-code/blob/7e7a8fd21e007541c867f66d82cfb5767cbf2316/sc-display-code.php#L139

This could be with a simple:
`WP_CONTENT_DIR . '/downloads/code/' . $post_id . '.txt';`

**Comment by simplycomputing** [comment]
Yes, looks like a very good idea.

**Comment by bahiirwa** [comment]
Moving to https://github.com/ClassicPress-research/sc-display-code/issues
