### ISSUE TITLE
Escape Autosave of the post

### ISSUE THREAD

**Issue by bahiirwa** [simplycomputing/sc-display-code#3]
ClassicPress has autosaving mechanisms of the post which need to be escaped as such

```
// Escape on autosave of the post.
    if ( wp_is_post_autosave( $post_id ) || wp_is_post_revision( $post_id ) ) {
        return;
    }
```

https://github.com/simplycomputing/sc-display-code/blob/7e7a8fd21e007541c867f66d82cfb5767cbf2316/sc-display-code.php#L146

the `save_post` action also provides the post ID so we do not need to call the global $post here.

**Comment by simplycomputing** [comment]
OK. I'm not really up with all that so will go with whatever you think.

**Comment by bahiirwa** [comment]
Moving to https://github.com/ClassicPress-research/sc-display-code/issues
