### ISSUE TITLE
Proper way to enqueue the scripts and styles

### ISSUE THREAD

**Issue by bahiirwa** [simplycomputing/sc-display-code#4]
There is a proper way to enqueue these in the Head or body for ClassicPress

https://github.com/simplycomputing/sc-display-code/blob/7e7a8fd21e007541c867f66d82cfb5767cbf2316/sc-display-code.php#L17-L27

we need to use `wp_enqueue_scripts()`

**Comment by simplycomputing** [comment]
OK. Should we also look at hosting these files within the plugin rather than do external calls?

**Comment by bahiirwa** [comment]
Moving to https://github.com/ClassicPress-research/sc-display-code/issues
