### ISSUE TITLE
txt file not overwritten on save of post.

### ISSUE THREAD

**Issue by bahiirwa** [simplycomputing/sc-display-code#5]
I have unsusual behaviour on my server where the content of the txt file is not overwritten but rather more code is added to the file as I save. Is the same for you?

https://github.com/simplycomputing/sc-display-code/blob/7e7a8fd21e007541c867f66d82cfb5767cbf2316/sc-display-code.php#L134-L144

We could do a delete whenever, we save and write the file afresh

```
// Overwrite hack! Remove the existing file so as to write new one.
        if ( file_exists( $file ) ) {
            unlink( $file );
        }
```

**Comment by simplycomputing** [comment]
That is supposed to happen with the w+ mode parameter that is defined.

`'w+' - Open for reading and writing; place the file pointer at the beginning of the file and truncate the file to zero length. If the file does not exist, attempt to create it.`

Are you testing this on the CC site or your own server?

**Comment by bahiirwa** [comment]
Moving to https://github.com/ClassicPress-research/sc-display-code/issues
